// Code generated by 'malatd gen' command.
// DO NOT EDIT!

package args

import (
	"github.com/swxctx/malatd/binding"
)

// EmptyStruct alias of type struct {}
type EmptyStruct = binding.Empty

// ChatDoArgsV1 comment...
type ChatDoArgsV1 struct {
	// 厂商[1: 百度 2: 讯飞 3: 智谱]
	Platform int `json:"platform"`
	// 是否流式
	Stream bool `json:"stream"`
	// 对话内容
	Content string `json:"content"`
}

// ChatDoResultV1 comment...
type ChatDoResultV1 struct {
	Message string `json:"message"`
}
