// Code generated by 'malatd gen' command.
// DO NOT EDIT!

package api

import (
	td "github.com/swxctx/malatd"
	"github.com/swxctx/malatd/binding"

	"github.com/swxctx/goai/example/args"
	"github.com/swxctx/goai/example/logic"
)

// Do handler
func DoHandle(ctx *td.Context) {
	// bind arg
	arg := new(args.ChatDoArgsV1)
	if err := binding.Binder(ctx, arg); err != nil {
		ctx.RenderRerr(td.RerrInternalServer.SetReason(err.Error()))
		return
	}

	// api logic
	result, rerr := logic.V1_Chat_Do(ctx, arg)
	if rerr != nil {
		ctx.RenderRerr(rerr)
		return
	}
	ctx.Render(result)
}
